### PR TITLE
Write solid tests

### LINKED ISSUE #10: Write solid tests
The parsing is still really buggy.  There are a handful of unit tests in here but I think we should have a lot more, and have the Example project have a working UITextView which we can put an attributed string into and test it manually. No reproduction steps

### PR DESCRIPTION
**Pull request by SerenadeX**
Fixes #10 
Also includes an example app where you can test out the functionality of the parser.  Uses [RichTextVC](https://github.com/LyokoTech/RichTextVC-iOS) to run a text view that shows the parsing. To verify, run the tests in Xcode

### CODE REVIEW

File: Example/TSSwiftMarkdownParser/TextViewController.swift [hunk 1]
```diff
@@ -0,0 +1,151 @@
...
+        view.addSubview(textView)
+        view.backgroundColor = UIColor.blueColor()
+        view.addConstraints(NSLayoutConstraint.constraintsWithVisualFormat("V:|[textView]|", options: [], metrics: nil, views: views))
+        view.addConstraints(NSLayoutConstraint.constraintsWithVisualFormat("H:|[textView]|", options: [], metrics: nil, views: views))
+        textView.becomeFirstResponder()
+    }
+    
+    func parse() {
+        if parsed {
+            //Switch to attributedString
```
Comment (brandenr) [inline Example/TSSwiftMarkdownParser/TextViewController.swift]: There should be a space after the //

File: Example/TSSwiftMarkdownParser/TextViewController.swift [hunk 2]
```diff
@@ -0,0 +1,151 @@
...
+            textView.attributedText = TSSwiftMarkdownParser.standardParser.attributedStringFromMarkdown(textView.text)
+        } else {
+            //Switch to markdownString
```
Comment (brandenr) [inline Example/TSSwiftMarkdownParser/TextViewController.swift]: Same

File: Example/TSSwiftMarkdownParser/TextViewController.swift [hunk 3]
```diff
@@ -0,0 +1,151 @@
...
+            textView.attributedText = NSAttributedString(string: textView.attributedText?.markdownString() ?? "")
+        }
+        parseButton.tintColor = parsed ? UIColor.blueColor() : UIColor.redColor()
```
Comment (brandenr) [inline Example/TSSwiftMarkdownParser/TextViewController.swift]: UIColor isn't needed since tintColor is a UIColor

File: Example/TSSwiftMarkdownParser/TextViewController.swift [hunk 4]
```diff
@@ -0,0 +1,151 @@
...
+        parsed = !parsed
+    }
+    
+
```
Comment (brandenr) [inline Example/TSSwiftMarkdownParser/TextViewController.swift]: Remove extra empty line

File: Example/Tests/NSAttributedString+MarkdownTests.swift [hunk 5]
```diff
@@ -36,17 +36,50 @@ class NSAttributedStringTests: XCTestCase {
...
             "hello",
             "**something**",
-            "bible **studies**   \n**open the door**"
+            "bible **studies**\n**open the door**"
         ]
         
         strings.forEach { assertRoundTripFromMarkdownString($0) }
     }
     
+
```
Comment (brandenr) [inline Example/Tests/NSAttributedString+MarkdownTests.swift]: Undo adding extra line

File: Pod/Classes/NSAttributedString+Markdown.swift [hunk 6]
```diff
@@ -85,6 +84,9 @@ public extension NSAttributedString {
                     if !characterOnBulletedListLine && !characterOnNumberedListLine {
                         stringToAppend += String(closingString.characters.reverse())
                     }
+                    
+                    characterOnBulletedListLine = characterOnBulletedListLine ? false : characterOnBulletedListLine
```
Comment (nickmshelley) [inline Pod/Classes/NSAttributedString+Markdown.swift]: This is the same as `characterOnBulletedListLine = false`.

File: Pod/Classes/NSAttributedString+Markdown.swift [hunk 7]
```diff
@@ -85,6 +84,9 @@ public extension NSAttributedString {
...
+                    characterOnNumberedListLine = characterOnNumberedListLine ? false : characterOnNumberedListLine
```
Comment (nickmshelley) [inline Pod/Classes/NSAttributedString+Markdown.swift]: Same as above.

File: Pod/Classes/TSBaseParser.swift [hunk 8]
```diff
@@ -26,7 +26,8 @@ public class TSBaseParser {
     private var parsingPairs = [TSExpressionBlockPair]()
     
     public func attributedStringFromMarkdown(markdown: String) -> NSAttributedString? {
-        return attributedStringFromMarkdown(markdown, attributes: defaultAttributes)
+        let attributedString = attributedStringFromMarkdown(markdown, attributes: defaultAttributes)
+        return attributedString
```
Comment (nickmshelley) [inline Pod/Classes/TSBaseParser.swift]: Was this change to make breakpoints easier? It's not a big deal but I like how it was before better.

File: Pod/Classes/TSSwiftMarkdownParser.swift [hunk 9]
```diff
@@ -98,6 +100,19 @@ public class TSSwiftMarkdownParser: TSBaseParser {
         strongAndEmphasisAttributes = [NSFontAttributeName: strongAndEmphasisFont]
         
         if withDefaultParsing {
+            
+            addNumberedListParsingWithMaxLevel(0, leadFormattingBlock: { (attributedString, range, level) in
```
Comment (nickmshelley) [inline Pod/Classes/TSSwiftMarkdownParser.swift]: Does a max level of zero mean something, or is it just a sentinel indicating there's no max level? If it's the latter it should probably be an optional instead.

Comment (SerenadeX) [inline Pod/Classes/TSSwiftMarkdownParser.swift]: Its a starting point.  If there is more levels of indentation then this handles them.  But we start at 0

Comment (nickmshelley) [inline Pod/Classes/TSSwiftMarkdownParser.swift]: I'm looking at where it's used and it seems like a sentinel to me: `let regexString = NSString(format: pattern, maxLevel > 0 ? "\(maxLevel)" : "") as String`. I think it should be optional instead so the intent is clear.

File: Pod/Classes/TSSwiftMarkdownParser.swift [hunk 10]
```diff
@@ -98,6 +100,19 @@ public class TSSwiftMarkdownParser: TSBaseParser {
...
+                var listString = ""
```
Comment (nickmshelley) [inline Pod/Classes/TSSwiftMarkdownParser.swift]: `let indentString = String(count: level, repeatedValue: Character("\u{00A0}"))`

File: Pod/Classes/TSSwiftMarkdownParser.swift (hunk 9 above)
Comment (nickmshelley) [inline Pod/Classes/TSSwiftMarkdownParser.swift]: Why is 0 hard coded in there anyway?

File: Pod/Classes/TSSwiftMarkdownParser.swift [hunk 11]
```diff
@@ -110,9 +125,9 @@ public class TSSwiftMarkdownParser: TSBaseParser {
             addListParsingWithMaxLevel(0, leadFormattingBlock: { attributedString, range, level in
                 var listString = ""
```
Comment (nickmshelley) [inline Pod/Classes/TSSwiftMarkdownParser.swift]: `let indentString = String(count: level, repeatedValue: Character("\u{00A0}"))`

**Comment by nickmshelley** [comment]
.

File: Pod/Classes/TSSwiftMarkdownParser.swift (hunk 9 above)
Comment (SerenadeX) [inline Pod/Classes/TSSwiftMarkdownParser.swift]: The 0 is hard coded for the `standardParser` which includes all the rules by default.  You can add your own parsing rules and have the max level be bigger than 0.  If that is the case then the line you cited is to fill in the regex on how many levels it should look for the lead string.  The level when not being used here is used on the formattingBlock based on the length of the second match of the regex.  See lines 223-227

File: Pod/Classes/TSSwiftMarkdownParser.swift (hunk 10 above)
Comment (stephanheilner) [inline Pod/Classes/TSSwiftMarkdownParser.swift]: You may also want to create a private static let for this since you use it in multiple places.

**Comment by SerenadeX** [comment]
I think I am actually going to remove the leveled list.  Its not working at all, and I'm not sure how to solve it.  It isn't necessary to have it now either.  I've made an issue so I don't forget about this but for now I'm going to remove it.  It is issue #12.

**Comment by nickmshelley** [comment]
Sounds great!

**Comment by ghost** [comment]
Your pull request doesn't follow our guidelines. Please fix the following:
- Pull request description must include verification steps.

[Click here](https://app.gitmagic.io/LyokoTech/TSSwiftMarkdownParser/11/91a66016-68ae-41ee-a580-0ec15842dc4f/e830f6a9-6495-46b5-af84-602d39bd0790) for details. Leave a comment when you've fixed these errors and we will revalidate.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, the title and description now looks good! :bowtie:

**Comment by SerenadeX** [comment]
Ignore gitmagic.  I'm just testing it on this repo.  If travis passes then it passes the tests

File: Example/Tests/NSAttributedString+MarkdownTests.swift [hunk 12]
```diff
@@ -95,6 +95,15 @@ class NSAttributedStringTests: XCTestCase {
         XCTAssertEqual(attributedString.markdownString(), markdown)
     }
     
+    func testLevelledLists() {
+        let strings = [
+//            "+ Level One\n + Level Two\n  + Level Three",
```
Comment (nickmshelley) [inline Example/Tests/NSAttributedString+MarkdownTests.swift]: Why is this commented out?

File: Example/Tests/TSSwiftMarkdownParserTests.swift [hunk 13]
```diff
@@ -13,7 +13,12 @@ import TSSwiftMarkdownParser
 class TSSwiftMarkdownParserTests: XCTestCase {
     
     var parser = TSSwiftMarkdownParser(withDefaultParsing: false)
-    var standardParser = TSSwiftMarkdownParser.standardParser
+    var standardParser = TSSwiftMarkdownParser()
+    
+    override func setUp() {
+        parser = TSSwiftMarkdownParser(withDefaultParsing: false)
+        standardParser = TSSwiftMarkdownParser()
```
Comment (nickmshelley) [inline Example/Tests/TSSwiftMarkdownParserTests.swift:21]: Is this to clear state before each test?

File: Pod/Classes/TSSwiftMarkdownParser.swift [hunk 14]
```diff
@@ -100,47 +98,32 @@ public class TSSwiftMarkdownParser: TSBaseParser {
...
-                for _ in (level - 1).stride(to: 0, by: 1) {
-                    listString = "\(listString)\u{00A0}"
-                }
-                let substring = attributedString.attributedSubstringFromRange(range).string.stringByReplacingOccurrencesOfString(" ", withString: "\u{00A0}")
-                listString = "\(listString)\(substring)"
-                attributedString.replaceCharactersInRange(range, withString: listString)
+            addNumberedListParsingWithLeadFormattingBlock({ (attributedString, range, level) in
+                let substring = attributedString.attributedSubstringFromRange(range).string.stringByReplacingOccurrencesOfString(" ", withString: "\(nonBreakingSpaceCharacter)")
+                attributedString.replaceCharactersInRange(range, withString: "\(substring)")
             }) { attributedString, range, level in
```
Comment (nickmshelley) [inline Pod/Classes/TSSwiftMarkdownParser.swift]: Can you move this inside the parens? Using trailing closure syntax makes it unclear what this closure's purpose is.

File: Pod/Classes/TSSwiftMarkdownParser.swift [hunk 15]
```diff
@@ -100,47 +98,32 @@ public class TSSwiftMarkdownParser: TSBaseParser {
...
                 TSSwiftMarkdownParser.addAttributes(self.numberedListAttributes, atIndex: level - 1, toString: attributedString, range: range)
             }
             
             addEscapingParsing()
             addCodeEscapingParsing()
             
-            addHeaderParsingWithMaxLevel(0, leadFormattingBlock: { attributedString, range, level in
+            addHeaderParsingWithLeadFormattingBlock({ attributedString, range, level in
                 attributedString.replaceCharactersInRange(range, withString: "")
             }) { attributedString, range, level in
```
Comment (nickmshelley) [inline Pod/Classes/TSSwiftMarkdownParser.swift]: Put the closure inside the parens please.

File: Example/Tests/TSSwiftMarkdownParserTests.swift (hunk 13 above)
Comment (SerenadeX) [inline Example/Tests/TSSwiftMarkdownParserTests.swift:21]: Yes

**Comment by nickmshelley** [comment]
Looking good!

**Comment by nickmshelley** [comment]
👍
